runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:e8XNMvoTebwIKGlYRatL3pFe9026EGjgaeF34KlCNt4=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: file
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: booklist
  DB_USERNAME: root
  DB_PASSWORD: PawnCoder1!
  DB_SOCKET: "/cloudsql/booklist-206615:us-central1:booklist"

beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  cloud_sql_instances: "booklist-206615:us-central1:booklist"
